version: "3.8"

services:
  app:
    build: 
      context: ./app/
    container_name: app
    ports:
      - '8887:8888'
    stdin_open: true 
    tty: true
    restart: "on-failure"  
    volumes:
      - ./app:/app
