version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: app
    mem_limit: 4g
    ports:
      - "8887:8888"
    stdin_open: true
    tty: true
    restart: "on-failure"
    volumes:
      - .:/app