name: visualization
channels:
 - defaults
dependencies:
  - pip
  - pandas
  - numpy
  - jupyterlab
  - matplotlib
  - mapclassify
  - fiona
  - notebook
  - jupyter
  - ipykernel
  - folium
  - geopy
    